toby = Dog.create(name: "Toby", breed: "Goldendoodle", age: 1, picture: "https://www.dogtopia.com/baton-rouge/wp-content/uploads/sites/168/2017/06/dog-spa-pricing.jpg")
bailey = Dog.create(name: "Bailey", breed: "Maltese", age: 3, picture: "https://st2.depositphotos.com/1504385/11152/i/950/depositphotos_111528878-stock-photo-little-dog-at-spa.jpg")
diesel = Dog.create(name: "Diesel", breed: "Labrador", age: 2, picture: "http://www.puppyhavenatl.com/wp-content/uploads/2018/02/Grooming-Lab-Bath-1024x682.jpg")
chanel = Dog.create(name: "Chanel", breed: "Poodle", age: 13, picture: "https://pbs.twimg.com/media/DShCZrTUQAA0APO.jpg")
louie = Dog.create(name: "Louie", breed: "Bichon Frise", age: 4, picture: "http://fursidepetgrooming.com/wp-content/uploads/2016/07/dog-stock2-900x600-e1473085094762.png")
henry = Dog.create(name: "Henry", breed: "Pug", age: 1, picture: "https://startacus.net/uploads/image/iStock_000018349332XSmall.jpg")
jenn = Dog.create(name: "Jenn", breed: "Yorkie", age: 10, picture: "http://www.thepawspapetsalon.com/sink_image_copy.jpg")
max = Dog.create(name: "Max", breed: "Chow Chow", age: 2, picture: "https://static.wixstatic.com/media/012b63c2180a4d12a165261038c217e5.jpg/v1/fill/w_1170,h_520,al_c,q_85,usm_0.66_1.00_0.01/012b63c2180a4d12a165261038c217e5.webp")
brownie = Dog.create(name: "Brownie", breed: "Welsh Corgi", age: 4, picture: "http://www.lovemydogresortnaples.com/images/scene-5-main-logo.jpg")
mandy = Dog.create(name: "Mandy", breed: "Golden Retriever", age: 5, picture: "http://geekfishing.net/wp-content/uploads/2018/03/top-dog-grooming-750x474.jpg")

woofies = Groomer.create(name: "Woofie's", location: "111 Biscuit Circle")
barknscrub = Groomer.create(name: "Bark n' Scrub", location: "453 Doggie Street")
fromheadtotail = Groomer.create(name: "From Head to Tail", location: "990 Soft Fur Blvd")
doggystyle = Groomer.create(name: "Doggy Style", location: "1073 Cheese Treats Court")

service1 = Service.create(service: "Full Spa")
service2 = Service.create(service: "Color Treatment")
service3 = Service.create(service: "PAWdicure")
service4 = Service.create(service: "Shampoo & Conditioner")
service5 = Service.create(service: "Fabulous Skin Treatment")
service6 = Service.create(service: "Groom FURminator")
service7 = Service.create(service: "Bubble Bath with Rubber Duckies")
service8 = Service.create(service: "Ear Cleaning")
service9 = Service.create(service: "20min Brushing")

appt1 = Appointment.create(day: "Monday", dog: toby, groomer: woofies)
appt3 = Appointment.create(day: "Tuesday", dog: brownie, groomer: doggystyle)
appt4 = Appointment.create(day: "Wednesday", dog: mandy, groomer: fromheadtotail)
appt6 = Appointment.create(day: "Thursday", dog: louie, groomer: woofies)
appt8 = Appointment.create(day: "Friday", dog:jenn, groomer: doggystyle)
appt9 = Appointment.create(day: "Saturday", dog: diesel, groomer: barknscrub)
